version: "3.9"

services:
  php:
    image: php:8.3-fpm
    container_name: php
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app-network
    command: bash -c "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" && php composer-setup.php --install-dir=/usr/local/bin --filename=composer && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: Nikita
      POSTGRES_PASSWORD: 2008
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge